[package]
edition = "2021"
name = "blib"
version = "0.1.0"

[dependencies]
anyhow = "1.0.79"
base64 = "0.21.7"
bitcoin_hashes = "0.13.0"
bs58 = "0.5.0"
hex = "0.4.3"
k256 = "0.13.3"
log = "0.4.20"
rand = "0.8.5"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
